### ISSUE TITLE
Subfields of an Array fields are not rendered

### ISSUE THREAD

**Issue by hasheddan** [crdsdev/doc#102]
A field that has an array of objects is no longer rendering the fields of the object type in the array. For example, https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/BucketPolicy/v1alpha2#spec-forProvider-statements does not show all the fields in https://github.com/crossplane/provider-aws/blob/4e88c93f6c7c897d2842a125d0f1fe7f7a3243da/apis/s3/v1alpha2/bucketpolicy_types.go#L58

**Comment by hasheddan** [comment]
@RichiCoder1 I should have time to get to this soon, but feel free to jump in if you have bandwidth :+1:

**Comment by RichiCoder1** [comment]
I've noticed some small other issues so I'll jump on this :)

**Comment by hasheddan** [comment]
Awesome! Thanks so much!
