### ISSUE TITLE
Please add Keycloak Operator to the index

### ISSUE THREAD

**Issue by slaskawi** [crdsdev/doc#106]
Dear CRD Dev Maintainers,

Could you please add [Keycloak Operator](https://github.com/keycloak/keycloak-operator) to the index?

Thanks,
Sebastian Łaskawiec, Keycloak Operator Lead, Red Hat

**Comment by hasheddan** [comment]
doc will automatically index new repos from now on :)

https://twitter.com/hasheddan/status/1351254486581473281

**Comment by slaskawi** [comment]
Thanks @hasheddan !
