### ISSUE TITLE
Index on the fly based on requested path

### ISSUE THREAD

**Issue by khos2ow** [crdsdev/doc#119]
At the moment addition of a new repo is by either 1) filing an issue and a maintainer adds it to `deploy/config.yml` or 2) directly opening a PR for changing that same file. In both cases it is gated (and to some degree limited) by the maintainers' capacity.

Other approach can be taken (similar to [pkg.go.dev](https://pkg.go.dev/)) in which the indexing is done on the fly by processing the requested _page_. For example someone sends a request to `https://doc.crds.dev/github.com/org/project`, at this point either this project had been indexed before or not. If not, that can be queued to get picked up and indexed, otherwise it's been already indexed and the content can be rendered. Consecutively all the already indexed projects have to be requeued to get updated periodically.

This will make usage of [docs.crds.dev](https://docs.crds.dev/) way more user friendly and more flexible but at the same time the code needs to get refactored a lot (to implement some workers, queuing mechanism, etc) which might not be a very big deal. And also the backend infrastructure has to be changed a bit (to add more capacity, most probably add some sort of RDBS instead of a text file of _what_ to index, etc.)

**Comment by hasheddan** [comment]
@khos2ow this is the plan :) I have a private branch where I have switched to postgres backend and use a message queue to communicate between server and gitter. Hope to get it finished up and released soon!

**Comment by khos2ow** [comment]
Ooh nice!! :rocket: Let me know if I can lend a hand.

**Comment by hasheddan** [comment]
xref #99

**Comment by hasheddan** [comment]
doc will automatically index new repos from now on :)

https://twitter.com/hasheddan/status/1351254486581473281
