### ISSUE TITLE
Set Page Title to Include Details

### ISSUE THREAD

**Issue by tobru** [crdsdev/doc#128]
When browsing documentation and opening many CRD docs in browser tabs it would be very helpful when the page title includes more details about the CRD being looked at instead of just "Doc".

Proposed page title for example for https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.16.0:

`CRD Doc s3.aws.crossplane.io/Bucket`

More details could be included - of course - but this minimal extended page title would already help a lot.

**Comment by hasheddan** [comment]
@tobru good idea! Will get this updated :)
