### ISSUE TITLE
gateway-api seems to be misdetected

### ISSUE THREAD

**Issue by howardjohn** [crdsdev/doc#144]
https://doc.crds.dev/github.com/kubernetes-sigs/gateway-api

CRDs live here: https://github.com/kubernetes-sigs/gateway-api/blob/master/config/crd/bases/networking.x-k8s.io_backendpolicies.yaml

But do not show up

**Comment by hasheddan** [comment]
@howardjohn this has been fixed thanks to @RichiCoder1 :)
