### ISSUE TITLE
upbound/platform-ref-aws broken

### ISSUE THREAD

**Issue by luebken** [crdsdev/doc#155]
https://doc.crds.dev/github.com/upbound/platform-ref-aws defines a couple of CRDs but none of them are discovered but the project itself is listed.

**Comment by hasheddan** [comment]
@luebken I don’t believe platform-ref-aws defines any CRDs. There are compositions and XRDs, which are not currently indexed by Doc

**Comment by luebken** [comment]
🤦 yes. Makes sense. 

That said as we keep using doc.crds.dev for API reference and I wonder where a user could find out about all the CRDs that e.g. upbound/platform-ref-aws indirectly offers. Let's move this conversation to Slack.
