### ISSUE TITLE
Crds not rendered

### ISSUE THREAD

**Issue by abhilashjoseph** [crdsdev/doc#167]
The site currently just shows a blank page for all crds, looks like some cache / db flush is needed

```
GET https://unpkg.com/eventemitter3@5.0.0/umd/eventemitter3.min.js net::ERR_ABORTED 404

Uncaught ReferenceError: EventEmitter3 is not defined
    at v1alpha1@v22.3.3:79:17
```

**Comment by hasheddan** [comment]
Thanks for the report -- taking a look!

**Comment by hasheddan** [comment]
This has been fixed and is now live. Thanks @abhilashjoseph !

**Comment by abhilashjoseph** [comment]
> This has been fixed and is now live. Thanks @abhilashjoseph !

Thank you! it is working now!
