### ISSUE TITLE
The page is broken

### ISSUE THREAD

**Issue by fabioaraujopt** [crdsdev/doc#169]
This lib became unavailable:

`https://unpkg.com/react-table@7.8.0/dist/react-table.production.min.js`

This is making the JS break with:

`Uncaught ReferenceError: ReactTable is not defined`

**Comment by hasheddan** [comment]
@fabioaraujopt I am unable to reproduce this behavior -- are you still seeing it?

**Comment by hasheddan** [comment]
@fabioaraujopt I am going to close this for now, but please reopen if you are still seeing this behavior!
