### ISSUE TITLE
Make tag selection more discoverable

### ISSUE THREAD

**Issue by prasek** [crdsdev/doc#26]
### What seems to be the problem?
Just realized you can specify a tag in the URL, e.g. https://doc.crds.dev/github.com/crossplane/provider-gcp@v0.7.0, but this isn't discoverable for new users

Would be awesome to:
1) add links for latest 3 tags on main page as follow on to #23
2) provide an available tags<dropdown> so I can select the tags on this page

![image](https://user-images.githubusercontent.com/284840/79494985-c56add80-7fd8-11ea-8ea5-2d82046de30a.png)

**Comment by hasheddan** [comment]
Tags are now discoverable on each repo page :)
