### ISSUE TITLE
Please include github.com/giantswarm/apiextensions

### ISSUE THREAD

**Issue by marians** [crdsdev/doc#43]
https://github.com/giantswarm/apiextensions hosts a number of CRDs we are using at Giant Swarm. We'd like to see them in https://doc.crds.dev/

Thanks!

**Comment by hasheddan** [comment]
Thanks @marians! Will let you know when these CRDs are available (soon!) :)

**Comment by hasheddan** [comment]
doc will automatically index new repos from now on :)

https://twitter.com/hasheddan/status/1351254486581473281
