### ISSUE TITLE
Add cert-manager CRDs

### ISSUE THREAD

**Issue by mcristina422** [crdsdev/doc#49]
Add the https://github.com/jetstack/cert-manager CRDs

**Comment by hasheddan** [comment]
@mcristina422 awesome :) will do!

**Comment by mcristina422** [comment]
I tried figuring this out locally but couldn't. I hope https://github.com/crdsdev/doc/issues/28 includes a detailed process for adding a new set of CRDs

Awesome tool, cant wait to see it take off!

**Comment by hasheddan** [comment]
@mcristina422 definitely will add some better documentation! Thanks for making the attempt!

**Comment by hasheddan** [comment]
It looks like the conversion functions are not liking the templated tags, I might need to either remove those or try and run the build as part of the parsing :thinking:

**Comment by mcristina422** [comment]
I know that `doc` works by checking out a repo and using the committed CRDs but it seems like the only committed ones by cert-manager include the helm templates. This version is published and correct though

https://github.com/jetstack/cert-manager/releases/download/v0.15.0/cert-manager.crds.yaml

**Comment by hasheddan** [comment]
@mcristina422 yep! Also exploring #52 as a fix
