### ISSUE TITLE
Project list view - separate sortable columns for GVK

### ISSUE THREAD

**Issue by prasek** [crdsdev/doc#58]
Thanks for adding support for shoring the full GVK in the list view #56, that's a big improvement!

The other day I was reviewing [provider-aws](https://github.com/crossplane-provider-aws) CRDs with a contributor and we and we wanted to view the list of beta vs. alpha CRDs and wanted the ability to sort the CRDs by version as a separate field.

Would be awesome to support:
- separate sortable columns in the list view for group, version, and kind
- tighten the spacing of the columns so it's easier to read without jumping back and forth horizontally 
![image](https://user-images.githubusercontent.com/284840/82744156-89d6d800-9d29-11ea-9721-5cbe87668b8f.png)

Really liking the enhancements, this is a super useful tool!!

**Comment by hasheddan** [comment]
@prasek this has been implemented with sortable columns, starting with default alphabetical sorting of `Group` per @mcristina422 request in #46. Check it out at https://doc.crds.dev/github.com/crossplane/crossplane and let me know if you have any feedback :)
