### ISSUE TITLE
Collapse all button for sections

### ISSUE THREAD

**Issue by muvaf** [crdsdev/doc#71]
I just realized that I can click to `spec` and have it collapsed and loved it. A lot of time, I collapse all functions in my editor when I deal with a long page of code and then click through only the things I'd like.

I think it'd be great experience to have a button to collapse all fields and let people open one by one and discover the fields.

I can contribute if there are some pointers about how one could implement this.

**Comment by hasheddan** [comment]
@muvaf thanks for opening this :) It looks like this has gotten some support from others as well. I originally had them collapsed by default, but then expanded them based on a request from @negz. I think it would be pretty straightforward to add a button to "collapse all" as you suggest. Would you be fine with them being open by default, but then having this "collapse all" option?

**Comment by muvaf** [comment]
My personal preference would be to see them closed initially and explore the fields one by one by expanding the ones I wanted. Collapse all button is more useful when they are all expanded already such as now but if it's collapsed initially, I'm not sure how frequent I'd use collapse all button.

**Comment by hasheddan** [comment]
Fixed by #97
