### ISSUE TITLE
Add kubernetes-sigs/cluster-api-provider-aws

### ISSUE THREAD

**Issue by detiber** [crdsdev/doc#88]
It would be great to also add docs for kubernetes-sigs/cluster-api-provider-aws

**Comment by hasheddan** [comment]
@detiber thanks for opening this! Will add ASAP :slightly_smiling_face:

**Comment by hasheddan** [comment]
doc will automatically index new repos from now on :)

https://twitter.com/hasheddan/status/1351254486581473281
