### ISSUE TITLE
Migrate Styles to Halfmoon

### ISSUE THREAD

**Issue by RichiCoder1** [crdsdev/doc#96]
I'm planning to contribute some styling changes and new functionality. However one issue I've already run into is that while Bootstrap is a solid library, it's nigh impossible to theme without a local build step. In the spirit of keeping the templates basic and MVC style, I wanted to suggest (and do the effort to switch to) [Halfmoon](https://www.gethalfmoon.com/). It's a recent Bootstrap-inspired framework with the distinct difference of using CSS Variables for all theme functionality, meaning I can pull it from a CDN and customize it in browser.

**Comment by RichiCoder1** [comment]
Also provides out-of-the-box dark mode for #51 :)

**Comment by hasheddan** [comment]
@RichiCoder1 this looks awesome! Would definitely support any UI improvements.

**Comment by hasheddan** [comment]
Fixed by #97
